const strategies={
  '표상의 원리':[
    {title:'학습목표 조직화',desc:'전체-일부-소수로 학습목표 세분화하기'},
    {title:'질문의 다양화',desc:'학습자의 배경지식과 사전지식을 활성화하기 위한 학습자에게 적합한 질문하기'},
    {title:'미니 수업',desc:'학습자의 이해를 파악하며 어려움을 겪는 학생들에 대한 교수-학습적 조치하기'},
    {title:'그래픽조직자',desc:'시각적 의사전달 도구 활용하기'}
  ],
  '표현의 원리':[
    {title:'표현 방법 선택',desc:'학습자가 선호하는 방식의 표현 방법을 인정하기'},
    {title:'평가 체크리스트',desc:'자신의 학습과정을 모니터링하는 안내 제공하기'}
  ],
  '참여의 원리':[
    {title:'학습 속도의 다양화',desc:'학습자의 배움의 속도에 대해 배려하기'},
    {title:'상호작용 기회 제공',desc:'다양한 주제와 진도로 이루어지는 수업에서 학생-학생, 학생-교사간의 다중 네트워크 형성 독려하기'},
    {title:'차등적 과제',desc:'학생의 다양한 수준, 준비도, 흥미 등을 고려하여 조절가능한 과제를 제시하기'}
  ],
  '공통전략':[
    {title:'다양한 도구와 자료',desc:'학습자에 맞는 매체와 도구 자료 제공하기'},
    {title:'지속적이고 적절한 피드백',desc:'개인에 알맞은 피드백을 명확하게 하기'},
    {title:'유연한 집단 편성',desc:'학습활동에 따른 집단구성의 선택 허용하기'},
    {title:'학습계획서',desc:'학습 소재, 시간운영 계획, 학습 체크리스트 등 활용하기'}
  ]
};
const storeKey='udl-growth-v1';
const $=id=>document.getElementById(id);
const participationLabels={1:'거의 참여하지 않음',2:'일부 참여함',3:'절반 정도 참여함',4:'대부분 참여함',5:'안정적으로 참여함'};
const durationLabels={0:'거의 이어지지 않음',1:'1분 미만',2:'1~5분',3:'5~10분',4:'10분 이상',5:'활동이 끝날 때까지'};
const supportLabels={1:'지속적인 도움 필요',2:'자주 도움 필요',3:'가끔 도움 필요',4:'거의 스스로 참여함',5:'스스로 참여함'};
let state={students:[],records:[]};
function today(){return new Date().toISOString().slice(0,10)}
function clamp(v,min,max){return Math.min(max,Math.max(min,Number(v)||0))}
function participationLevel(r){let v=r.participationLevel??r.participationRate??r.engagement;if(v==null)return 3;v=Number(v);if(v>5){if(v<=20)return 1;if(v<=40)return 2;if(v<=60)return 3;if(v<=80)return 4;return 5}return clamp(Math.round(v),1,5)}
function durationLevel(r){let v=r.durationLevel??r.duration;if(v==null)return 2;v=Number(v);if(v<=0)return 0;if(v<1)return 1;if(v<=5)return 2;if(v<=10)return 3;return 4}
function supportLevel(r){let v=r.supportLevel;if(v!=null)return clamp(Math.round(v),1,5);let old=Number(r.intensity);if(!Number.isFinite(old))return 3;if(old>=3)return 1;if(old===2)return 2;if(old===1)return 3;return 5}
function problemBehaviorCount(r){return Number(r.problemBehaviorCount??r.frequency??0)}
function save(){localStorage.setItem(storeKey,JSON.stringify(state));render()}
function load(){try{state=JSON.parse(localStorage.getItem(storeKey))||state}catch{state={students:[],records:[]}}if(!state.students.length){state.students=[{id:crypto.randomUUID(),code:'A학생',grade:'3학년',definition:'수업 참여가 어려워지는 상황과 관찰할 참여 행동을 구체적으로 적어 주세요'}]}$('dateInput').value=today();renderStrategies();render()}
function renderStrategies(){const list=$('strategyList');list.innerHTML='';Object.entries(strategies).forEach(([group,items])=>{const section=document.createElement('section');section.className='strategy-group '+strategyClass(group);section.innerHTML='<h3>'+group+'</h3>';const table=document.createElement('div');table.className='strategy-table compact';table.innerHTML='<div class="strategy-header"><span>선택</span><span>수업 전략</span><span>설명</span></div>';items.forEach(item=>{const row=document.createElement('div');row.className='strategy-row';row.innerHTML='<span><input type="checkbox" value="'+group+': '+item.title+'"></span><strong>'+escapeHtml(item.title)+'</strong><details><summary>내용 보기</summary><em>'+escapeHtml(item.desc)+'</em></details>';table.append(row)});section.append(table);list.append(section)})}
function strategyClass(group){return group.replace(/[^가-힣A-Za-z0-9]/g,'')}
function render(){renderStudents();renderRecords();renderSummary();drawChart();drawInsightCharts();updateSeedButton()}
function isSampleRecord(r){const strategies=(r.strategies||[]).join('|');return !!r.isSample||strategies.includes('표상: 시각적 일과표')||strategies.includes('표상의 원리: 그래픽조직자')||String(r.toolMedia||'').includes('태블릿 선택 활동')||String(r.toolMedia||'').includes('그림카드')}
function hasSampleRecords(){return state.records.some(isSampleRecord)}
function updateSeedButton(){const button=$('seedButton');if(!button)return;button.textContent=hasSampleRecords()?'예시 지우기':'예시 자료';button.classList.toggle('danger',hasSampleRecords());button.classList.toggle('soft',!hasSampleRecords())}
function renderStudents(){const select=$('studentSelect');select.innerHTML='';state.students.forEach(s=>{const opt=document.createElement('option');opt.value=s.id;opt.textContent=s.code;select.append(opt)});$('studentCards').innerHTML=state.students.map(s=>'<article class="card"><div class="card-head"><strong>'+escapeHtml(s.code)+'</strong><button class="soft" onclick="deleteStudent(\''+s.id+'\')">삭제</button></div><p><span class="pill">'+escapeHtml(s.grade||'학년 미입력')+'</span></p><p>'+escapeHtml(s.definition||'조작적 정의 미입력')+'</p></article>').join('')}
function renderRecords(){const sorted=[...state.records].sort((a,b)=>b.date.localeCompare(a.date));$('recordList').innerHTML=sorted.slice(0,12).map(r=>{const stu=state.students.find(s=>s.id===r.studentId);return '<article class="record"><div class="record-head"><strong>'+r.date+' · '+escapeHtml(stu?.code||'삭제된 학생')+'</strong><span class="pill">참여 '+participationLevel(r)+'/5</span></div><p>'+escapeHtml(r.subject||'교과 미입력')+' / '+escapeHtml(r.period)+' / '+participationLabels[participationLevel(r)]+(r.toolMedia?' / 도구·매체: '+escapeHtml(r.toolMedia):'')+'</p><p>참여 유지: '+durationLabels[durationLevel(r)]+' · 도움: '+supportLabels[supportLevel(r)]+' · 문제 행동 '+problemBehaviorCount(r)+'회</p><p>'+escapeHtml(r.strategies.join(', ')||'UDL 전략 미선택')+'</p>'+(r.note?'<p>'+escapeHtml(r.note)+'</p>':'')+'</article>'}).join('')}
function renderSummary(){const records=state.records;$('recordCount').textContent=records.length;if(!records.length){$('avgFrequency').textContent='0';$('avgEngagement').textContent='0/5';$('changeRate').textContent='-';$('interpretation').textContent='기록을 추가하면 관찰 기간의 수업 참여 변화 양상이 표시됩니다. 인과관계는 단정하지 않습니다.';return}const avgProblemBehavior=records.reduce((s,r)=>s+problemBehaviorCount(r),0)/records.length;const avgParticipation=records.reduce((s,r)=>s+participationLevel(r),0)/records.length;$('avgFrequency').textContent=avgProblemBehavior.toFixed(1)+'회';$('avgEngagement').textContent=avgParticipation.toFixed(1)+'/5';const ordered=[...records].sort((a,b)=>a.date.localeCompare(b.date));const mid=Math.floor(ordered.length/2)||1;const before=ordered.slice(0,mid);const after=ordered.slice(mid);let text='자료가 더 쌓이면 전반부와 후반부의 수업 참여 단계를 비교합니다.';if(after.length){const b=before.reduce((s,r)=>s+participationLevel(r),0)/before.length;const a=after.reduce((s,r)=>s+participationLevel(r),0)/after.length;const diff=a-b;$('changeRate').textContent=(diff>0?'+':'')+diff.toFixed(1);const dir=diff>0?'높아지는':diff<0?'낮아지는':'유지되는';text='관찰 기간의 전반부 참여 평균 '+b.toFixed(1)+'/5, 후반부 참여 평균 '+a.toFixed(1)+'/5로 '+dir+' 양상이 나타났습니다. UDL 지원의 인과적 효과로 단정하지 않고, 건강 상태·과제 난이도·환경 요인을 함께 검토하세요.'}else{$('changeRate').textContent='-'}$('interpretation').textContent=text}
function drawChart(){const canvas=$('trendChart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;paintChartBackground(ctx,w,h);const byDate={};state.records.forEach(r=>{byDate[r.date]??={problemBehavior:0,participation:0,count:0};byDate[r.date].problemBehavior+=problemBehaviorCount(r);byDate[r.date].participation+=participationLevel(r);byDate[r.date].count++});const data=Object.entries(byDate).sort(([a],[b])=>a.localeCompare(b)).map(([date,v])=>({date,problemBehavior:v.problemBehavior,participation:v.participation/v.count}));drawGrid(ctx,w,h);ctx.fillStyle='#c7d0df';ctx.font='700 14px Arial';ctx.fillText('문제 행동',14,34);ctx.fillText('참여 단계',14,58);if(!data.length){drawEmpty(ctx,w,h,'아직 표시할 기록이 없습니다');return}const maxD=Math.max(5,...data.map(d=>d.problemBehavior));const x=i=>70+(w-110)*(data.length===1?.5:i/(data.length-1));const yD=v=>315-(v/maxD)*240;const yP=v=>315-(v/5)*240;line(data,d=>x(data.indexOf(d)),d=>yD(d.problemBehavior),'#ff6b5f');line(data,d=>x(data.indexOf(d)),d=>yP(d.participation),'#54d17a');data.forEach((d,i)=>{drawDateLabel(ctx,d.date,x(i),344)});ctx.fillStyle='#ff6b5f';ctx.fillText('문제 행동',730,30);ctx.fillStyle='#54d17a';ctx.fillText('수업 참여',840,30)}
function drawDateLabel(ctx,date,x,y){const label=date.slice(5).replace('-', '.');ctx.font='700 12px Arial';const width=ctx.measureText(label).width+14;ctx.fillStyle='rgba(15,24,41,.9)';roundRect(ctx,x-width/2,y-15,width,21,8);ctx.fill();ctx.strokeStyle='rgba(174,184,202,.28)';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#d7deea';ctx.fillText(label,x-width/2+7,y)}
function drawInsightCharts(){const principleData=summarizeByPrinciple();const mediaData=summarizeByMedia();updateInsightText('principleInsight',principleData,'UDL 원리');updateInsightText('mediaInsight',mediaData,'도구·매체');drawBarChart($('principleChart'),principleData,'평균 참여 단계 1~5점');drawBarChart($('mediaChart'),mediaData,'평균 참여 단계 1~5점')}
function normalizePrinciple(group){if(group.includes('표현'))return '표현';if(group.includes('표상'))return '표상';if(group.includes('참여'))return '참여';if(group.includes('공통'))return '공통';return ''}
function summarizeByPrinciple(){const map={표현:{sum:0,count:0},표상:{sum:0,count:0},참여:{sum:0,count:0},공통:{sum:0,count:0}};state.records.forEach(r=>{(r.strategies||[]).forEach(s=>{const group=normalizePrinciple(String(s).split(':')[0].trim());if(map[group]){map[group].sum+=participationLevel(r);map[group].count++}})});return Object.entries(map).map(([name,v])=>({name,avg:v.count?v.sum/v.count:0,count:v.count,color:name==='표현'?'#8ab4ff':name==='표상'?'#54d17a':name==='참여'?'#ffad6b':'#d9a8ff'}))}
function summarizeByMedia(){const map={};state.records.forEach(r=>{String(r.toolMedia||'').split(/[,，、/]+/).map(v=>v.trim()).filter(Boolean).forEach(name=>{map[name]??={sum:0,count:0};map[name].sum+=participationLevel(r);map[name].count++})});return Object.entries(map).map(([name,v])=>({name,avg:v.sum/v.count,count:v.count,color:'#8ab4ff'})).sort((a,b)=>b.avg-a.avg||b.count-a.count).slice(0,6)}
function updateInsightText(id,data,label){const el=$(id);if(!el)return;const valid=data.filter(d=>d.count).sort((a,b)=>b.avg-a.avg||b.count-a.count);if(!valid.length){el.textContent='아직 비교할 기록이 없습니다. 기록이 쌓이면 자동으로 요약됩니다.';return}const top=valid[0];el.textContent='현재 기록에서는 '+top.name+' '+label+'를 사용한 수업에서 평균 참여가 가장 높게 나타났습니다. ('+top.avg.toFixed(1)+'/5, '+top.count+'건)'}
function drawBarChart(canvas,data,title){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;paintChartBackground(ctx,w,h);ctx.fillStyle='#f7f9ff';ctx.font='700 16px Arial';ctx.fillText(title,20,32);ctx.fillStyle='#aeb8ca';ctx.font='12px Arial';ctx.fillText('막대가 길수록 해당 기록의 평균 참여 단계가 높습니다.',20,52);if(!data.length||data.every(d=>!d.count)){drawEmpty(ctx,w,h,'기록이 쌓이면 표시됩니다');return}const chartX=128,chartY=76,barH=30,gap=16,max=5;data.forEach((d,i)=>{const y=chartY+i*(barH+gap);const width=(w-chartX-58)*(d.avg/max);ctx.fillStyle=d.count?'#d7deea':'#6d7788';ctx.font='700 13px Arial';ctx.fillText(trimLabel(d.name,11),18,y+20);ctx.fillStyle='rgba(255,255,255,.08)';roundRect(ctx,chartX,y,w-chartX-58,barH,10);ctx.fill();if(d.count){ctx.fillStyle=d.color;roundRect(ctx,chartX,y,Math.max(4,width),barH,10);ctx.fill()}ctx.fillStyle='#f7f9ff';ctx.font='700 13px Arial';const label=d.count?d.avg.toFixed(1)+'/5 · '+d.count+'건':'기록 없음';ctx.fillText(label,Math.min(chartX+width+8,w-92),y+20)})}
function paintChartBackground(ctx,w,h){ctx.clearRect(0,0,w,h);const gradient=ctx.createLinearGradient(0,0,0,h);gradient.addColorStop(0,'#121d30');gradient.addColorStop(1,'#0f1829');ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h)}
function drawGrid(ctx,w,h){ctx.strokeStyle='rgba(174,184,202,.18)';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=70+i*61;ctx.beginPath();ctx.moveTo(70,y);ctx.lineTo(w-34,y);ctx.stroke()}}
function drawEmpty(ctx,w,h,text){ctx.fillStyle='#aeb8ca';ctx.font='700 20px Arial';ctx.fillText(text,Math.max(24,w/2-130),h/2)}
function roundRect(ctx,x,y,w,h,r){const radius=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+radius,y);ctx.arcTo(x+w,y,x+w,y+h,radius);ctx.arcTo(x+w,y+h,x,y+h,radius);ctx.arcTo(x,y+h,x,y,radius);ctx.arcTo(x,y,x+w,y,radius);ctx.closePath()}
function trimLabel(text,max){return text.length>max?text.slice(0,max-1)+'…':text}
function line(data,fx,fy,color){const ctx=$('trendChart').getContext('2d');ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=3;ctx.beginPath();data.forEach((d,i)=>{const xx=fx(d),yy=fy(d);if(i)ctx.lineTo(xx,yy);else ctx.moveTo(xx,yy)});ctx.stroke();data.forEach(d=>{ctx.beginPath();ctx.arc(fx(d),fy(d),5,0,Math.PI*2);ctx.fill()})}
function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
window.deleteStudent=id=>{if(confirm('이 학생과 관련 기록을 삭제할까요?')){state.students=state.students.filter(s=>s.id!==id);state.records=state.records.filter(r=>r.studentId!==id);save()}}
$('studentForm').addEventListener('submit',e=>{e.preventDefault();state.students.push({id:crypto.randomUUID(),code:$('studentCodeInput').value.trim(),grade:$('gradeInput').value.trim(),definition:$('definitionInput').value.trim()});e.target.reset();save()});
$('recordForm').addEventListener('submit',e=>{e.preventDefault();const checked=[...document.querySelectorAll('#strategyList input:checked')].map(i=>i.value);const participation=Number($('engagementInput').value||3);const duration=Number($('durationInput').value||2);const support=Number($('supportLevelInput').value||3);const difficulty=Number($('frequencyInput').value||0);state.records.push({id:crypto.randomUUID(),studentId:$('studentSelect').value,date:$('dateInput').value,subject:$('subjectInput').value.trim(),toolMedia:$('toolMediaInput').value.trim(),period:$('periodInput').value,strategies:checked,participationLevel:participation,participationRate:participation,engagement:participation,durationLevel:duration,duration:duration,supportLevel:support,intensity:support,problemBehaviorCount:difficulty,frequency:difficulty,antecedent:$('antecedentInput').value.trim(),behavior:$('behaviorInput').value.trim(),consequence:$('consequenceInput').value.trim(),note:$('noteInput').value.trim()});document.querySelectorAll('#strategyList input').forEach(i=>i.checked=false);$('frequencyInput').value=0;$('toolMediaInput').value='';$('durationInput').value=2;$('supportLevelInput').value=3;$('engagementInput').value=3;$('antecedentInput').value='';$('behaviorInput').value='';$('consequenceInput').value='';$('noteInput').value='';save()});
$('seedButton').addEventListener('click',()=>{if(hasSampleRecords()){if(confirm('예시 자료만 삭제할까요? 직접 입력한 기록은 유지됩니다.')){state.records=state.records.filter(r=>!isSampleRecord(r));save()}return}const id=state.students[0]?.id;if(!id)return;const base=new Date();state.records=state.records.filter(r=>!isSampleRecord(r));[3,3,4,4,4,5,4,5,5,5].forEach((p,i)=>{const d=new Date(base);d.setDate(base.getDate()-9+i);state.records.push({id:crypto.randomUUID(),isSample:true,studentId:id,date:d.toISOString().slice(0,10),subject:i%2?'수학':'국어',toolMedia:i%2?'태블릿 선택 활동, 단계별 안내':'시각적 일과표, 그림카드',period:(i%5+1)+'교시',strategies:i%4===0?['표현의 원리: 표현 방법 선택','공통전략: 다양한 도구와 자료']:i%4===1?['표상의 원리: 그래픽조직자','참여의 원리: 학습 속도의 다양화']:i%4===2?['참여의 원리: 차등적 과제','공통전략: 지속적이고 적절한 피드백']:['표상의 원리: 질문의 다양화','표현의 원리: 학습선택판'],participationLevel:p,participationRate:p,engagement:p,durationLevel:i<2?2:i<6?3:4,duration:i<2?2:i<6?3:4,supportLevel:i<3?2:i<7?3:4,intensity:i<3?2:i<7?3:4,problemBehaviorCount:Math.max(0,6-i),frequency:Math.max(0,6-i),antecedent:'과제 전환과 소음',behavior:'시각 단서를 보고 과제에 참여함',consequence:'선택권과 짧은 확인 피드백 제공',note:i===5?'배경사건: 평소와 다른 좌석 배치. 좌석 위치 조정 후 참여 유지 증가':''})});save()});
$('csvButton').addEventListener('click',()=>{const rows=[['날짜','학생코드','교과','사용한도구와매체','시간대','UDL전략','수업참여단계','참여유지','도움필요정도','문제행동횟수','선행사건','관찰된행동참여모습','결과','특이사항']];state.records.forEach(r=>{const s=state.students.find(x=>x.id===r.studentId);rows.push([r.date,s?.code||'',r.subject,r.toolMedia||'',r.period,r.strategies.join('|'),participationLabels[participationLevel(r)],durationLabels[durationLevel(r)],supportLabels[supportLevel(r)],problemBehaviorCount(r),r.antecedent,r.behavior,r.consequence,r.note])});const csv='﻿'+rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='udl-observation.csv';a.click();URL.revokeObjectURL(a.href)});
$('backupButton').addEventListener('click',()=>{const payload={app:'UDL 행동성장 기록',version:1,exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='udl-record-backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)});
$('restoreInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const text=await file.text();const data=JSON.parse(text);const next=data.state||data;if(!Array.isArray(next.students)||!Array.isArray(next.records))throw new Error('invalid');if(confirm('백업 파일의 학생과 기록을 이 기기에 불러올까요? 현재 이 기기의 기록은 백업 내용으로 바뀝니다.')){state={students:next.students,records:next.records};save()}}catch{alert('백업 파일을 읽을 수 없습니다. 이 앱에서 저장한 JSON 백업 파일인지 확인해 주세요.')}finally{e.target.value=''}});
$('printButton').addEventListener('click',()=>window.print());
$('clearButton').addEventListener('click',()=>{if(confirm('이 작업은 이 기기에 저장된 기록만 삭제합니다. 삭제한 기록은 복구할 수 없습니다. 정말 삭제하시겠습니까?')){localStorage.removeItem(storeKey);state={students:[],records:[]};load()}});
let deferredPrompt;$('installButton').classList.remove('hidden');$('installButton').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;return}alert('휴대폰에서는 브라우저 메뉴에서 홈 화면에 추가 또는 앱 설치를 눌러 설치할 수 있습니다. PC 크롬/엣지에서는 주소창 오른쪽의 설치 아이콘을 눌러 주세요.')});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installButton').classList.remove('hidden')});if('serviceWorker'in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{})}load();