const strategies={참여:['선택권 제공','과제 분량 조절','예측 가능한 일과','휴식카드','선호 활동 활용'],표상:['사진·그림 자료','시각적 일과표','단계별 안내','모델링','핵심어 강조'],표현:['그림으로 응답','AAC 사용','손가락 선택','응답 방식 선택','과제 단계 분절']};
const storeKey='udl-growth-v1';
const $=id=>document.getElementById(id);
let state={students:[],records:[]};
function today(){return new Date().toISOString().slice(0,10)}
function save(){localStorage.setItem(storeKey,JSON.stringify(state));render()}
function load(){try{state=JSON.parse(localStorage.getItem(storeKey))||state}catch{state={students:[],records:[]}}if(!state.students.length){state.students=[{id:crypto.randomUUID(),code:'A학생',grade:'3학년',definition:'과제 제시 후 10초 이상 자리에서 이탈하거나, 3초 이상 큰 소리로 말하는 행동'}]}$('dateInput').value=today();renderStrategies();render()}
function renderStrategies(){const list=$('strategyList');list.innerHTML='';Object.entries(strategies).forEach(([group,items])=>items.forEach(item=>{const label=document.createElement('label');label.className='check';label.innerHTML='<input type="checkbox" value="'+group+': '+item+'"><span>'+group+' · '+item+'</span>';list.append(label)}))}
function render(){renderStudents();renderRecords();renderSummary();drawChart()}
function renderStudents(){const select=$('studentSelect');select.innerHTML='';state.students.forEach(s=>{const opt=document.createElement('option');opt.value=s.id;opt.textContent=s.code;select.append(opt)});$('studentCards').innerHTML=state.students.map(s=>'<article class="card"><div class="card-head"><strong>'+escapeHtml(s.code)+'</strong><button class="soft" onclick="deleteStudent(\''+s.id+'\')">삭제</button></div><p><span class="pill">'+escapeHtml(s.grade||'학년 미입력')+'</span></p><p>'+escapeHtml(s.definition||'조작적 정의 미입력')+'</p></article>').join('')}
function renderRecords(){const sorted=[...state.records].sort((a,b)=>b.date.localeCompare(a.date));$('recordList').innerHTML=sorted.slice(0,12).map(r=>{const stu=state.students.find(s=>s.id===r.studentId);return '<article class="record"><div class="record-head"><strong>'+r.date+' · '+escapeHtml(stu?.code||'삭제된 학생')+'</strong><span class="pill">빈도 '+r.frequency+'회</span></div><p>'+escapeHtml(r.subject||'교과 미입력')+' / '+escapeHtml(r.period)+' / 참여율 '+r.engagement+'%</p><p>'+escapeHtml(r.strategies.join(', ')||'UDL 전략 미선택')+'</p>'+(r.note?'<p>'+escapeHtml(r.note)+'</p>':'')+'</article>'}).join('')}
function renderSummary(){const records=state.records;$('recordCount').textContent=records.length;if(!records.length){$('avgFrequency').textContent='0';$('avgEngagement').textContent='0%';$('changeRate').textContent='-';$('interpretation').textContent='기록을 추가하면 관찰 기간의 변화 양상이 표시됩니다. 인과관계는 단정하지 않습니다.';return}const avg=n=>records.reduce((s,r)=>s+Number(r[n]||0),0)/records.length;$('avgFrequency').textContent=avg('frequency').toFixed(1);$('avgEngagement').textContent=Math.round(avg('engagement'))+'%';const ordered=[...records].sort((a,b)=>a.date.localeCompare(b.date));const mid=Math.floor(ordered.length/2)||1;const before=ordered.slice(0,mid);const after=ordered.slice(mid);let text='자료가 더 쌓이면 전반부와 후반부 평균을 비교합니다.';if(after.length){const b=before.reduce((s,r)=>s+r.frequency,0)/before.length;const a=after.reduce((s,r)=>s+r.frequency,0)/after.length;const rate=b?((a-b)/b*100):0;$('changeRate').textContent=(rate>0?'+':'')+rate.toFixed(1)+'%';const dir=rate<0?'감소':rate>0?'증가':'유지';text='관찰 기간의 전반부 평균 '+b.toFixed(1)+'회, 후반부 평균 '+a.toFixed(1)+'회로 '+dir+' 양상이 나타났습니다. UDL 지원의 인과적 효과로 단정하지 않고, 건강 상태·과제 난이도·환경 요인을 함께 검토하세요.'}else{$('changeRate').textContent='-'}$('interpretation').textContent=text}
function drawChart(){const canvas=$('trendChart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);const byDate={};state.records.forEach(r=>{byDate[r.date]??={frequency:0,engagement:0,count:0};byDate[r.date].frequency+=Number(r.frequency);byDate[r.date].engagement+=Number(r.engagement);byDate[r.date].count++});const data=Object.entries(byDate).sort(([a],[b])=>a.localeCompare(b)).map(([date,v])=>({date,frequency:v.frequency,engagement:v.engagement/v.count}));ctx.strokeStyle='#d9e1e3';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=40+i*62;ctx.beginPath();ctx.moveTo(60,y);ctx.lineTo(w-30,y);ctx.stroke()}ctx.fillStyle='#647176';ctx.font='14px Arial';ctx.fillText('빈도',18,34);ctx.fillText('참여율',12,64);if(!data.length){ctx.fillStyle='#647176';ctx.font='22px Arial';ctx.fillText('아직 표시할 기록이 없습니다',330,180);return}const maxF=Math.max(5,...data.map(d=>d.frequency));const x=i=>60+(w-100)*(data.length===1?.5:i/(data.length-1));const yF=v=>320-(v/maxF)*260;const yE=v=>320-(v/100)*260;line(data,d=>x(data.indexOf(d)),d=>yF(d.frequency),'#c65339');line(data,d=>x(data.indexOf(d)),d=>yE(d.engagement),'#25636f');data.forEach((d,i)=>{ctx.fillStyle='#647176';ctx.font='12px Arial';ctx.fillText(d.date.slice(5),x(i)-16,344)});ctx.fillStyle='#c65339';ctx.fillText('행동 빈도',760,30);ctx.fillStyle='#25636f';ctx.fillText('참여율',840,30)}
function line(data,fx,fy,color){const ctx=$('trendChart').getContext('2d');ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=3;ctx.beginPath();data.forEach((d,i)=>{const xx=fx(d),yy=fy(d);if(i)ctx.lineTo(xx,yy);else ctx.moveTo(xx,yy)});ctx.stroke();data.forEach(d=>{ctx.beginPath();ctx.arc(fx(d),fy(d),5,0,Math.PI*2);ctx.fill()})}
function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
window.deleteStudent=id=>{if(confirm('이 학생과 관련 기록을 삭제할까요?')){state.students=state.students.filter(s=>s.id!==id);state.records=state.records.filter(r=>r.studentId!==id);save()}}
$('studentForm').addEventListener('submit',e=>{e.preventDefault();state.students.push({id:crypto.randomUUID(),code:$('studentCodeInput').value.trim(),grade:$('gradeInput').value.trim(),definition:$('definitionInput').value.trim()});e.target.reset();save()});
$('recordForm').addEventListener('submit',e=>{e.preventDefault();const checked=[...document.querySelectorAll('#strategyList input:checked')].map(i=>i.value);state.records.push({id:crypto.randomUUID(),studentId:$('studentSelect').value,date:$('dateInput').value,subject:$('subjectInput').value.trim(),period:$('periodInput').value,strategies:checked,frequency:Number($('frequencyInput').value||0),duration:Number($('durationInput').value||0),intensity:Number($('intensityInput').value||0),engagement:Number($('engagementInput').value||0),antecedent:$('antecedentInput').value.trim(),behavior:$('behaviorInput').value.trim(),consequence:$('consequenceInput').value.trim(),note:$('noteInput').value.trim()});document.querySelectorAll('#strategyList input').forEach(i=>i.checked=false);$('frequencyInput').value=0;$('durationInput').value=0;$('engagementInput').value=80;$('noteInput').value='';save()});
$('seedButton').addEventListener('click',()=>{const id=state.students[0]?.id;if(!id)return;const base=new Date();state.records=[];[6,7,5,6,4,4,3,4,3,2].forEach((f,i)=>{const d=new Date(base);d.setDate(base.getDate()-9+i);state.records.push({id:crypto.randomUUID(),studentId:id,date:d.toISOString().slice(0,10),subject:i%2?'수학':'국어',period:(i%5+1)+'교시',strategies:['참여: 선택권 제공','표상: 시각적 일과표'],frequency:f,duration:f*1.5,intensity:f>5?3:2,engagement:62+i*3,antecedent:'과제 전환',behavior:'자리 이탈 또는 큰소리',consequence:'시각 단서와 짧은 휴식 제공',note:i===5?'좌석 위치 변경':''})});save()});
$('csvButton').addEventListener('click',()=>{const rows=[['날짜','학생코드','교과','시간대','UDL전략','빈도','지속시간','강도','참여율','A','B','C','특이사항']];state.records.forEach(r=>{const s=state.students.find(x=>x.id===r.studentId);rows.push([r.date,s?.code||'',r.subject,r.period,r.strategies.join('|'),r.frequency,r.duration,r.intensity,r.engagement,r.antecedent,r.behavior,r.consequence,r.note])});const csv='﻿'+rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='udl-observation.csv';a.click();URL.revokeObjectURL(a.href)});
$('printButton').addEventListener('click',()=>window.print());
$('clearButton').addEventListener('click',()=>{if(confirm('모든 자료를 삭제할까요?')){localStorage.removeItem(storeKey);state={students:[],records:[]};load()}});
let deferredPrompt;$('installButton').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installButton').classList.add('hidden')}});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installButton').classList.remove('hidden')});if('serviceWorker'in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{})}load();