const storeKey='udl-growth-v1';
const $=id=>document.getElementById(id);
const appUrl='https://yuu8409-oss.github.io/udl-growth-record/';
const participationLabels={1:'거의 참여 못함',2:'조금 참여함',3:'지원 시 참여 유지',4:'대부분 참여함',5:'스스로 참여함'};
const activityTags=['발표·말하기','쓰기','읽기','듣기','만들기','그리기','조작활동','신체·놀이활동','계산활동','기타'];
const principleNames=['표상 지원','표현 지원','참여 지원','공통 지원'];
const strategies={
  '표상 지원':[['학습목표 조직화','학습 목표와 절차를 시각적으로 정리하기'],['질문 다양화','학생의 배경지식을 떠올릴 수 있는 질문 제공'],['미니 수업','어려워하는 부분을 짧게 다시 설명하기'],['그래픽조직자','개념, 순서, 관계를 시각 자료로 보여 주기']],
  '표현 지원':[['표현 방법 선택','말, 글, 그림, 카드 등 다양한 표현 방식 허용'],['평가 체크리스트','학생이 자신의 수행 과정을 확인할 안내 제공']],
  '참여 지원':[['학습 속도 다양화','학생의 준비도와 속도에 맞게 조절하기'],['상호작용 기회 제공','교사-학생, 학생-학생 간 상호작용 기회 만들기'],['차등화 과제','수준과 준비도에 맞게 과제 난이도 조절하기'],['모델링 지원','또래, 교사, 보조 인력의 시범 제공']],
  '공통 지원':[['다양한 도구와 자료','학생에게 맞는 매체와 도구 제공'],['지속적이고 적절한 피드백','개인의 수행에 맞는 명확한 피드백 제공'],['유연한 집단 편성','활동에 맞는 집단 구성을 선택하게 하기'],['학습계획표','수업 절차, 시간 운영, 체크리스트 제공']]
};
let state={students:[],records:[]};
let selectedParticipation=null;
let showAllRecords=false;
let resultSelectionTouched=false;
let chartPoints=[];
let hoveredChartRecordId=null;
let selectedChartRecordId=null;
let selectedPeriod='2weeks';

function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function today(){return new Date().toISOString().slice(0,10)}
function uid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random().toString(16).slice(2)}
function clamp(v,min,max){return Math.min(max,Math.max(min,Number(v)||0))}
function save(){localStorage.setItem(storeKey,JSON.stringify(state));render()}
function isExampleItem(value){return value?.isExample===true||value?.isSample===true}
function normalizeStoredData(){const before=JSON.stringify(state);state.students=state.students.map(({isSample,...student})=>isSample?{...student,isExample:true}:student);state.records=state.records.map(({isSample,...record})=>isSample?{...record,isExample:true}:record);const removableIds=new Set(state.students.filter(s=>{const code=String(s?.code||'').trim();const hasRecord=state.records.some(r=>r.studentId===s.id);return !code||(code==='기능점검학생'&&s.grade==='테스트')||(code==='새학생'&&!String(s.grade||'').trim()&&!String(s.definition||'').trim()&&!hasRecord)||(code==='A학생'&&s.definition==='수업 참여 흐름을 관찰할 학생'&&!hasRecord)}).map(s=>s.id));if(removableIds.size){state.students=state.students.filter(s=>!removableIds.has(s.id));state.records=state.records.filter(r=>!removableIds.has(r.studentId))}return before!==JSON.stringify(state)}
function load(){try{state=JSON.parse(localStorage.getItem(storeKey))||state}catch{state={students:[],records:[]}} if(!Array.isArray(state.students))state.students=[]; if(!Array.isArray(state.records))state.records=[];if(normalizeStoredData())localStorage.setItem(storeKey,JSON.stringify(state));$('dateInput').value=today(); setupTabs(); renderStrategies(); setupSubjectControl(); setupActivityTags(); setupScoreGuide(); setupParticipationButtons(); setupDifficultyControl(); setupChartEvents(); setupShareLink(); bindEvents(); render()}
function studentById(id){return state.students.find(s=>s.id===id)}
function studentCode(id){return studentById(id)?.code||'학생'}
function periodOrder(value){const text=String(value||'');const match=text.match(/\d+/);if(match)return Number(match[0]);if(text.includes('방과'))return 99;return 50}
function compareRecordsAsc(a,b){return String(a.date).localeCompare(String(b.date))||periodOrder(a.period)-periodOrder(b.period)||String(a.id).localeCompare(String(b.id))}
function compareRecordsDesc(a,b){return compareRecordsAsc(b,a)}
function latestStudentId(){const latest=[...state.records].sort(compareRecordsDesc)[0];return latest?.studentId||state.students[0]?.id||''}
function participationLevel(r){let v=r.participationLevel??r.participationRate??r.engagement;if(v==null||v==='')return 3;v=Number(v);if(v>5){if(v<=20)return 1;if(v<=40)return 2;if(v<=60)return 3;if(v<=80)return 4;return 5}return clamp(Math.round(v),1,5)}
function difficultyCount(r){const exact=Number(r.difficultyExactCount);if(Number.isFinite(exact)&&exact>0)return exact;if(r.difficultyLevel==='many')return 4;const level=Number(r.difficultyLevel);if(Number.isFinite(level))return level;return Number(r.problemBehaviorCount??r.frequency??0)||0}
function difficultyText(r){const c=difficultyCount(r);if(c<=0)return'없었음';if(c===1)return'1회';if(c<=3)return'2~3회';return c>4?'여러 번('+c+'회)':'여러 번'}
function subjectText(r){return r.subject||'과목 미기록'}
function normalizeTags(value){if(Array.isArray(value))return value.filter(Boolean);return String(value||'').split(/[,|]/).map(x=>x.trim()).filter(Boolean)}
function activityList(r){const raw=[...normalizeTags(r.contextTags),...normalizeTags(r.toolMedia)].filter(Boolean);const out=[];raw.forEach(tag=>{const base=tag.startsWith('기타:')?'기타':tag;if(activityTags.includes(base)&&!out.includes(tag))out.push(tag)});return out}
function strategyLabel(v){return String(v||'').replace(/^[^:]+:\s*/,'')}
function strategyPrinciple(v){const text=String(v||'');return principleNames.find(n=>text.startsWith(n+':'))||'공통 지원'}
function countItems(records,getter){const counts=new Map();records.forEach(r=>getter(r).forEach(item=>{if(item)counts.set(item,(counts.get(item)||0)+1)}));return [...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))}
function formatCounts(counts,empty='기록이 더 필요해요'){return counts.length?counts.slice(0,4).map(([n,c])=>n+' '+c+'회').join(', '):empty}
function average(records){return records.length?records.reduce((sum,r)=>sum+participationLevel(r),0)/records.length:0}

function setupTabs(){document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));button.classList.add('active');$('tab-'+button.dataset.tab).classList.add('active');if(button.dataset.tab==='results')requestAnimationFrame(()=>drawChart(filteredRecordsForSelected()))}))}
function renderStrategies(){const list=$('strategyList');list.innerHTML='';Object.entries(strategies).forEach(([group,items])=>{const section=document.createElement('section');section.className='strategy-group';section.innerHTML='<h3>'+escapeHtml(group)+'</h3>';items.forEach(([title,desc])=>{const label=document.createElement('label');label.className='check';label.innerHTML='<input type="checkbox" value="'+escapeHtml(group+': '+title)+'"><span><strong>'+escapeHtml(title)+'</strong><small>'+escapeHtml(desc)+'</small></span>';section.append(label)});list.append(section)})}
function setupSubjectControl(){const update=()=>{const other=$('subjectInput').value==='기타';$('subjectOtherWrap').classList.toggle('hidden',!other);if(!other)$('subjectOtherInput').value=''};$('subjectInput').addEventListener('change',update);update()}
function setupActivityTags(){const details=document.querySelector('.activity-tag-field');const label=document.querySelector('.activity-summary-label');const update=()=>{const tags=selectedActivityTags();label.textContent=details.open?'▾ 활동 닫기':'▸ 활동';$('activitySelectionSummary').textContent=tags.length?'선택됨: '+(tags.length<=2?tags.join(', '):tags.length+'개'):'';details.dataset.hasSelection=tags.length?'true':'false';const hasOther=document.querySelector('.activity-tag[data-tag="기타"]').classList.contains('selected');$('activityOtherWrap').classList.toggle('hidden',!hasOther);if(!hasOther)$('activityOtherInput').value=''};document.querySelectorAll('.activity-tag').forEach(button=>button.addEventListener('click',()=>{button.classList.toggle('selected');button.setAttribute('aria-pressed',button.classList.contains('selected'));update()}));details.addEventListener('toggle',update);$('activityOtherInput').addEventListener('input',update);update()}
function selectedActivityTags(){const tags=[...document.querySelectorAll('.activity-tag.selected')].map(b=>b.dataset.tag);const other=$('activityOtherInput').value.trim();return tags.map(t=>t==='기타'&&other?'기타: '+other:t)}
function resetActivityTags(){document.querySelectorAll('.activity-tag').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false')});$('activityOtherInput').value='';document.querySelector('.activity-tag-field').open=false;document.querySelector('.activity-summary-label').textContent='▸ 활동';$('activitySelectionSummary').textContent=''}
function setupScoreGuide(){const guide=document.querySelector('.score-guide');guide.addEventListener('toggle',()=>{guide.querySelector('summary').textContent=guide.open?'▾ 점수 기준 닫기':'▸ 점수 기준 보기'})}
function setupParticipationButtons(){document.querySelectorAll('.participation-option').forEach(button=>button.addEventListener('click',()=>selectParticipation(Number(button.dataset.level))))}
function selectParticipation(level){selectedParticipation=level;$('engagementInput').value=level||'';document.querySelectorAll('.participation-option').forEach(button=>button.classList.toggle('selected',Number(button.dataset.level)===level));$('participationError').textContent=''}
function setupDifficultyControl(){const update=()=>{const many=$('difficultyLevelInput').value==='many';$('difficultyExactWrap').classList.toggle('hidden',!many);if(!many)$('difficultyExactInput').value=''};$('difficultyLevelInput').addEventListener('change',update);update()}
function setupShareLink(){const button=$('copyAppLinkButton');const status=$('copyAppLinkStatus');if(!button||!status)return;const fallbackCopy=()=>{const input=document.createElement('textarea');input.value=appUrl;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();const copied=document.execCommand('copy');input.remove();if(!copied)throw new Error('copy failed')};button.addEventListener('click',async()=>{try{if(navigator.clipboard&&window.isSecureContext){try{await navigator.clipboard.writeText(appUrl)}catch{fallbackCopy()}}else{fallbackCopy()}button.textContent='복사됨';status.textContent='접속 링크를 복사했습니다.';setTimeout(()=>{button.textContent='접속 링크 복사';status.textContent=''},2200)}catch{status.textContent='링크를 길게 눌러 복사해 주세요.'}})}
function downloadAppPackage(){const a=document.createElement('a');a.href='UDL-app-download.zip?v=121';a.download='UDL로 함께 성장하는 우리 앱 다운로드.zip';document.body.appendChild(a);a.click();a.remove()}
function bindEvents(){
 $('recordForm').addEventListener('submit',e=>{e.preventDefault();if(!state.students.some(s=>!isExampleItem(s))){$('participationError').textContent='관리 탭에서 관찰 대상 학생을 먼저 추가해 주세요.';return}if(!selectedParticipation){$('participationError').textContent='참여 점수를 선택해 주세요.';return}const subject=$('subjectInput').value==='기타'?($('subjectOtherInput').value.trim()||'기타'):$('subjectInput').value;const activities=selectedActivityTags();const selectedStrategies=[...document.querySelectorAll('#strategyList input:checked')].map(i=>i.value);const difficultyLevel=$('difficultyLevelInput').value;const exact=Number($('difficultyExactInput').value)||0;state.records.push({id:uid(),studentId:$('studentSelect').value,date:$('dateInput').value||today(),period:$('periodInput').value,subject,contextTags:activities.join(', '),toolMedia:activities.join(', '),strategies:selectedStrategies,participationLevel:selectedParticipation,participationRate:selectedParticipation,engagement:selectedParticipation,difficultyLevel,difficultyExactCount:difficultyLevel==='many'?exact:0,problemBehaviorCount:difficultyLevel==='many'?Math.max(exact,4):Number(difficultyLevel)||0,frequency:difficultyLevel==='many'?Math.max(exact,4):Number(difficultyLevel)||0,antecedent:$('antecedentInput').value.trim(),behavior:$('behaviorInput').value.trim(),consequence:$('consequenceInput').value.trim(),note:''});document.querySelectorAll('#strategyList input').forEach(i=>i.checked=false);selectParticipation(null);resetActivityTags();$('difficultyLevelInput').value='0';$('difficultyExactInput').value='';$('antecedentInput').value='';$('behaviorInput').value='';$('consequenceInput').value='';showAllRecords=false;save();document.querySelector('.tab[data-tab="results"]').click()});
 $('studentForm').addEventListener('submit',e=>{e.preventDefault();const code=$('studentCodeInput').value.trim();if(!code){$('studentFormError').textContent='학생 코드를 입력해 주세요.';$('studentCodeInput').focus();return}$('studentFormError').textContent='';state.students.push({id:uid(),code,grade:$('gradeInput').value.trim(),definition:$('definitionInput').value.trim()});$('studentForm').reset();save()});$('studentCodeInput').addEventListener('input',()=>{$('studentFormError').textContent=''});
 $('resultStudentSelect').addEventListener('change',()=>{resultSelectionTouched=true;showAllRecords=false;render()});
 document.querySelectorAll('.period-tab').forEach(button=>button.addEventListener('click',()=>{selectedPeriod=button.dataset.period;showAllRecords=false;selectedChartRecordId=null;hoveredChartRecordId=null;clearChartDetail();render()}));
 $('toggleAllRecordsButton').addEventListener('click',()=>{showAllRecords=!showAllRecords;renderRecordList(filteredRecordsForSelected())});
 $('resultExampleButton').addEventListener('click',addExampleData);$('clearExampleButton').addEventListener('click',removeExampleData);$('csvButton').addEventListener('click',downloadCsv);$('backupButton').addEventListener('click',backupData);$('restoreInput').addEventListener('change',restoreData);$('printButton').addEventListener('click',prepareReportAndPrint);$('clearButton').addEventListener('click',()=>{if(confirm('이 기기에 저장된 기록을 모두 삭제할까요?')){localStorage.removeItem(storeKey);window.location.reload()}});
 window.addEventListener('beforeprint',()=>{document.querySelectorAll('#contextDetails,.context-analysis-box,.record').forEach(el=>el.open=true);document.querySelectorAll('.interpretation').forEach(el=>el.open=false)});
 document.querySelectorAll('.summary-toggle').forEach(button=>button.addEventListener('click',()=>{const groups=allSummaryGroups();const names=groups[button.dataset.group]||[];$('summaryStudentList').classList.remove('hidden');$('summaryStudentList').textContent=names.length?names.join(', '):'해당 학생이 없습니다.'}));
 $('installButton').addEventListener('click',downloadAppPackage);window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();window.deferredInstallPrompt=event})
}

function render(){renderStudents();renderResults()}
function renderStudents(){const actualStudents=state.students.filter(s=>!isExampleItem(s));const hasExample=state.students.some(isExampleItem);const selected=$('resultStudentSelect').value;const recordStudent=$('studentSelect').value;$('studentSelect').innerHTML='';if(!actualStudents.length){const option=document.createElement('option');option.value='';option.textContent='학생을 먼저 추가해 주세요';$('studentSelect').append(option)}else{actualStudents.forEach(s=>{const option=document.createElement('option');option.value=s.id;option.textContent=s.code;$('studentSelect').append(option)})}$('studentSelect').disabled=!actualStudents.length;$('recordSaveButton').disabled=!actualStudents.length;$('resultExampleButton').disabled=hasExample;$('clearExampleButton').disabled=!hasExample;if(recordStudent&&actualStudents.some(s=>s.id===recordStudent))$('studentSelect').value=recordStudent;$('resultStudentSelect').innerHTML='<option value="">학생을 선택해 주세요</option>'+(actualStudents.length?'<option value="all">전체 학생 요약</option>':'');state.students.forEach(s=>{const option=document.createElement('option');option.value=s.id;option.textContent=s.code;$('resultStudentSelect').append(option)});let next=selected&&state.students.some(s=>s.id===selected)?selected:selected==='all'&&actualStudents.length?'all':latestStudentId();if(resultSelectionTouched&&selected==='')next='';$('resultStudentSelect').value=next;$('studentCountBadge').textContent=actualStudents.length+'명';$('studentCards').innerHTML=actualStudents.length?actualStudents.map(s=>'<article class="card"><div class="card-head"><strong>'+escapeHtml(s.code)+'</strong><span class="pill">'+escapeHtml(s.grade||'학년 미기록')+'</span></div><p>'+escapeHtml(s.definition||'특성 기록 없음')+'</p></article>').join(''):'<div class="student-empty-state"><strong>아직 관찰 대상 학생이 없습니다.</strong><p>학생 코드를 입력한 뒤 학생을 추가하면 수업 참여 흐름을 기록할 수 있습니다.</p></div>'}
function selectedStudentId(){return $('resultStudentSelect').value}
function recordsForSelected(){return recordsForStudent(selectedStudentId())}
function recordsForStudent(id){return state.records.filter(r=>r.studentId===id).sort(compareRecordsAsc)}
function periodMeta(){return selectedPeriod==='1month'?{label:'최근 1개월 기준',description:'최근 1개월 기록을 기준으로 참여 흐름과 UDL 지원을 정리했습니다.'}:selectedPeriod==='all'?{label:'전체 기록 기준',description:'저장된 전체 기록을 기준으로 참여 흐름과 UDL 지원을 정리했습니다.'}:{label:'최근 2주 기준',description:'최근 2주 기록을 기준으로 참여 흐름과 UDL 지원을 정리했습니다.'}}
function filterRecordsByPeriod(records){if(selectedPeriod==='all')return [...records];const end=new Date(today()+'T23:59:59');const start=new Date(end);if(selectedPeriod==='1month')start.setMonth(start.getMonth()-1);else start.setDate(start.getDate()-13);start.setHours(0,0,0,0);return records.filter(r=>{const date=new Date(String(r.date)+'T00:00:00');return !Number.isNaN(date.getTime())&&date>=start&&date<=end})}
function filteredRecordsForSelected(){return filterRecordsByPeriod(recordsForSelected())}
function resultEmptyMessage(){return selectedStudentId()?'선택한 기간에 기록이 없습니다. 다른 기간을 선택하거나 새 기록을 추가해 주세요.':'학생을 선택하거나 기록을 추가해 주세요.'}
function updatePeriodUI(hasRecords){const meta=periodMeta();document.querySelectorAll('.period-tab').forEach(button=>{const active=button.dataset.period===selectedPeriod;button.classList.toggle('active',active);button.setAttribute('aria-selected',active?'true':'false')});$('periodDescription').textContent=meta.description;$('corePeriodBadge').textContent=meta.label;$('udlPeriodBadge').textContent=meta.label;$('udlPeriodEmpty').textContent=resultEmptyMessage();$('udlPeriodEmpty').classList.toggle('hidden',hasRecords);$('udlReviewGrid').classList.toggle('hidden',!hasRecords)}
function renderResults(){const id=selectedStudentId();const allMode=id==='all';$('allSummary').classList.toggle('hidden',!allMode);$('individualResults').classList.toggle('hidden',allMode);if(allMode){renderAllSummary();clearChart();return}const records=id?filterRecordsByPeriod(recordsForStudent(id)):[];updatePeriodUI(records.length>0);renderRecentFlow(records);renderRecordList(records);renderChart(records);renderInsights(records);renderPrincipleUsage(records);renderContextAnalysis(records);renderContextSummaries(records);renderNextLessonDirections(records)}
function allSummaryGroups(){const weekAgo=new Date();weekAgo.setDate(weekAgo.getDate()-7);const groups={weekly:[],up:[],same:[],watch:[]};state.students.filter(s=>!isExampleItem(s)).forEach(s=>{const rs=recordsForStudent(s.id);if(rs.some(r=>new Date(r.date)>=weekAgo))groups.weekly.push(s.code);if(rs.length>=2){const levels=rs.slice(-4).map(participationLevel);const diff=levels.at(-1)-levels[0];if(diff>=1)groups.up.push(s.code);else if(diff<=-1)groups.watch.push(s.code);else groups.same.push(s.code)}});return groups}
function renderAllSummary(){const groups=allSummaryGroups();$('weeklyStudentCount').textContent=groups.weekly.length+'명';$('improvedStudentCount').textContent=groups.up.length+'명';$('steadyStudentCount').textContent=groups.same.length+'명';$('watchStudentCount').textContent=groups.watch.length+'명'}
function renderRecentFlow(records){const recent=records.slice(-5);const supportCounts=countItems(records,r=>(r.strategies||[]).map(strategyLabel));if(!records.length){$('recentFlowCards').innerHTML='<article class="period-empty-card">'+escapeHtml(resultEmptyMessage())+'</article>';return}const levels=recent.map(participationLevel);const avg=average(recent);const diff=levels.length>=2?levels.at(-1)-levels[0]:0;const flow=levels.length<2?'기록 1개':diff>0?'참여가 높아지는 흐름':diff<0?'다시 살펴볼 흐름':'비슷하게 유지';const frequent=supportCounts.length?supportCounts.slice(0,2).map(([n,c])=>n+' '+c+'회').join(', '):'기록된 지원이 없어요';$('recentFlowCards').innerHTML='<article class="summary-card accent-card accent-green"><span>최근 참여 흐름</span><strong>'+escapeHtml(flow)+'</strong><small>최근 기록: '+levels.map(v=>v+'점').join(' → ')+'</small></article><article class="summary-card accent-card accent-blue"><span>최근 '+recent.length+'회 평균</span><strong>'+avg.toFixed(1)+'점</strong><small>선택한 기간 안의 최근 기록 기준입니다.</small></article><article class="summary-card accent-card accent-purple"><span>자주 기록된 UDL 지원</span><strong>'+escapeHtml(frequent)+'</strong><small>선택한 기간에서 기록된 UDL 지원입니다.</small></article>'}
function renderRecordList(records){const sorted=[...records].reverse();const visible=showAllRecords?sorted:sorted.slice(0,3);$('recordList').innerHTML=visible.map(recordCard).join('') || '<p class="empty-note">'+escapeHtml(resultEmptyMessage())+'</p>';const button=$('toggleAllRecordsButton');button.classList.toggle('hidden',sorted.length<=3);button.textContent=showAllRecords?'최근 3개만 보기':'전체 기록 보기'}
function recordCard(r){const acts=activityList(r);const strs=r.strategies||[];return '<details class="record compact-record"><summary><div><strong>'+escapeHtml(r.date)+'</strong><span>'+escapeHtml(r.period||'시간 미기록')+' · '+escapeHtml(subjectText(r))+'</span></div><div class="record-badges"><span class="pill">'+participationLevel(r)+'점 '+escapeHtml(participationLabels[participationLevel(r)])+'</span><span class="pill muted">활동 '+escapeHtml(acts.join(', ')||'미선택')+'</span><span class="pill muted">UDL '+strs.length+'개</span><span class="pill muted">어려웠던 순간 '+escapeHtml(difficultyText(r))+'</span></div></summary><div class="record-detail"><p><strong>UDL 지원 전략 전체</strong><br>'+escapeHtml(strs.map(strategyLabel).join(', ')||'없음')+'</p><p><strong>수업 참여가 어려웠던 순간</strong><br>'+escapeHtml(difficultyText(r))+'</p><p><strong>선행사건</strong><br>'+escapeHtml(r.antecedent||'기록 없음')+'</p><p><strong>관찰된 참여 모습</strong><br>'+escapeHtml(r.behavior||'기록 없음')+'</p><p><strong>결과</strong><br>'+escapeHtml(r.consequence||'기록 없음')+'</p></div></details>'}
function rankListHtml(counts,empty='기록이 더 필요해요'){if(!counts.length)return '<p class="rank-empty">'+escapeHtml(empty)+'</p>';return counts.slice(0,3).map(([name,count])=>'<p><strong>'+escapeHtml(name)+'</strong><span>'+count+'회</span></p>').join('')}
function renderInsights(records){const highSupport=countItems(records.filter(r=>participationLevel(r)>=4),r=>(r.strategies||[]).map(strategyLabel));const lowSupports=countItems(records.filter(r=>participationLevel(r)<=2),r=>(r.strategies||[]).map(strategyLabel));const lowActivities=countItems(records.filter(r=>participationLevel(r)<=2),activityList);const lowMixed=[...lowSupports.map(([n,c])=>['지원: '+n,c]),...lowActivities.map(([n,c])=>['활동: '+n,c])].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));$('topSupport').innerHTML=rankListHtml(highSupport,'높은 참여 기록이 더 필요해요');$('lowActivity').innerHTML=rankListHtml(lowMixed,'낮은 참여 기록이 더 필요해요')}
function renderSupportParticipation(records){const groups=new Map();records.forEach(r=>(r.strategies||[]).forEach(strategy=>{const label=strategyLabel(strategy);if(!groups.has(label))groups.set(label,[]);groups.get(label).push(r)}));const rows=[...groups.entries()].sort((a,b)=>b[1].length-a[1].length||a[0].localeCompare(b[0]));$('strategyParticipationList').innerHTML=rows.map(([label,rs])=>{const avg=average(rs).toFixed(1);const high=rs.filter(r=>participationLevel(r)>=4).length;return '<p><strong>'+escapeHtml(label)+'</strong><span>평균 '+avg+'점 · 기록 '+rs.length+'회 · 높은 참여 기록 '+high+'회</span></p>'}).join('')||'<p>선택된 UDL 지원 기록이 더 필요해요.</p>'}
function renderPrincipleUsage(records){const groups=Object.fromEntries(principleNames.map(name=>[name,[]]));records.forEach(r=>{const selected=new Set((r.strategies||[]).map(strategyPrinciple));selected.forEach(name=>groups[name].push(r))});$('principleUsage').innerHTML=principleNames.map(name=>{const rs=groups[name];const avg=rs.length?average(rs).toFixed(1)+'점':'없음';return '<article><strong>'+escapeHtml(name)+'</strong><span>기록 '+rs.length+'회 · 평균 '+avg+'</span></article>'}).join('')}
function groupedSummary(records,getter){const groups=new Map();records.forEach(r=>getter(r).forEach(key=>{if(!key)return;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)}));return [...groups.entries()].sort((a,b)=>b[1].length-a[1].length||a[0].localeCompare(b[0]))}
function topTextValues(records,key){const counts=new Map();records.map(r=>String(r[key]||'').trim()).filter(Boolean).forEach(v=>counts.set(v,(counts.get(v)||0)+1));return [...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,3)}
function renderContextAnalysis(records){const box=$('contextAnalysis');if(!box)return;if(!records.length){box.innerHTML='<p class="analysis-empty">'+escapeHtml(resultEmptyMessage())+'</p>';return}const recent=records.slice(-5);const low=records.filter(r=>participationLevel(r)<=2);const high=records.filter(r=>participationLevel(r)>=4);const antecedents=topTextValues(recent,'antecedent');const behaviors=topTextValues(recent,'behavior');const consequences=topTextValues(recent,'consequence');const difficulty=countItems(records,r=>[difficultyText(r)]).filter(([name])=>name!=='없었음').slice(0,3);const highSupports=countItems(high,r=>(r.strategies||[]).map(strategyLabel)).slice(0,3);const lowActivities=countItems(low,activityList).slice(0,3);function line(title,items,empty){return '<article><h4>'+title+'</h4>'+(items.length?'<ul>'+items.map(([name,count])=>'<li>'+escapeHtml(name)+' <span>'+count+'회</span></li>').join('')+'</ul>':'<p>'+empty+'</p>')+'</article>'}box.innerHTML='<p class="analysis-note">최근 기록을 바탕으로 반복적으로 보이는 단서를 정리한 참고용 요약입니다. 원인이나 효과를 단정하지 않습니다.</p><div class="analysis-grid">'+line('자주 보인 선행사건',antecedents,'선행사건 기록이 더 필요해요.')+line('관찰된 참여 모습',behaviors,'참여 모습 기록이 더 필요해요.')+line('결과로 이어진 변화',consequences,'결과 기록이 더 필요해요.')+line('어려웠던 순간',difficulty,'어려웠던 순간 기록이 거의 없어요.')+line('높은 참여 기록의 UDL 지원',highSupports,'높은 참여 기록의 지원 선택이 더 필요해요.')+line('낮은 참여 기록의 활동',lowActivities,'낮은 참여 기록의 활동 태그가 더 필요해요.')+'</div>'}
function strengthRows(records,getter){const rows=groupedSummary(records,getter).map(([name,rs])=>({name,records:rs,count:rs.length,avg:average(rs)})).sort((a,b)=>b.avg-a.avg||b.count-a.count||a.name.localeCompare(b.name));if(!rows.length)return {top:[],rest:[]};const topAvg=rows[0].avg;let top=rows.filter(row=>Math.abs(row.avg-topAvg)<0.001);if(top.length>2)top=top.slice(0,2);if(top.length<2){const next=rows.filter(row=>!top.includes(row)).slice(0,2-top.length);top=[...top,...next]}const topNames=new Set(top.map(row=>row.name));return {top,rest:rows.filter(row=>!topNames.has(row.name))}}
function strengthHtml(summary,empty){if(!summary.top.length)return '<p class="strength-empty">'+escapeHtml(empty)+'</p>';const cards=summary.top.map((row,index)=>'<div class="strength-item '+(index===0?'best':'')+'"><div><span class="strength-badge">'+(index===0?'강점':'높은 참여')+'</span><strong>'+escapeHtml(row.name)+'</strong></div><p>최근 '+row.count+'회 기록 · <b>평균 '+row.avg.toFixed(1)+'점</b></p></div>').join('');const detail=summary.rest.length?'<details class="strength-more"><summary>자세히 보기</summary>'+summary.rest.map(row=>'<p><strong>'+escapeHtml(row.name)+'</strong><span>최근 '+row.count+'회 · 평균 '+row.avg.toFixed(1)+'점</span></p>').join('')+'</details>':'';return cards+detail}
function renderContextSummaries(records){if(!records.length){const message='<p class="strength-empty">'+escapeHtml(resultEmptyMessage())+'</p>';$('subjectSummaryList').innerHTML=message;$('activitySummaryList').innerHTML=message;return}$('subjectSummaryList').innerHTML=strengthHtml(strengthRows(records,r=>[subjectText(r)]),'과목 기록이 더 필요해요.');$('activitySummaryList').innerHTML=strengthHtml(strengthRows(records,r=>activityList(r)),'수업 활동 태그 기록이 더 필요해요.')}

function nearestChartPoint(canvas,e){if(!e||!chartPoints.length)return null;const p=pointerPos(canvas,e);return chartPoints.map(point=>({...point,d:Math.hypot(point.x-p.x,point.y-p.y)})).sort((a,b)=>a.d-b.d)[0]}
function setupChartEvents(){const canvas=$('trendChart');const hitRadius=48;const select=e=>{const nearest=nearestChartPoint(canvas,e);if(nearest&&nearest.d<hitRadius){selectedChartRecordId=nearest.record.id;hoveredChartRecordId=nearest.record.id;showChartRecordDetail(nearest.record);drawChart(filteredRecordsForSelected())}};canvas.addEventListener('click',select);canvas.addEventListener('touchstart',e=>select(e.touches[0]),{passive:true});canvas.addEventListener('mousemove',e=>{const nearest=nearestChartPoint(canvas,e);const next=nearest&&nearest.d<hitRadius?nearest.record.id:null;canvas.style.cursor=next?'pointer':'default';if(hoveredChartRecordId!==next){hoveredChartRecordId=next;drawChart(filteredRecordsForSelected())}});canvas.addEventListener('mouseleave',()=>{if(hoveredChartRecordId){hoveredChartRecordId=null;drawChart(filteredRecordsForSelected())}})}
function pointerPos(canvas,e){const rect=canvas.getBoundingClientRect();return{x:e.clientX-rect.left,y:e.clientY-rect.top}}
function clearChartDetail(){const detail=$('chartDetail');if(detail){detail.classList.add('hidden');detail.innerHTML=''}}
function clearChart(){const canvas=$('trendChart');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);chartPoints=[];clearChartDetail()}
function renderChart(records){requestAnimationFrame(()=>drawChart(records))}
function drawChart(records=filteredRecordsForSelected()){const canvas=$('trendChart');const ctx=canvas.getContext('2d');const dpr=window.devicePixelRatio||1;const pointCount=Math.max(1,records.length||1);const baseWidth=canvas.parentElement?.clientWidth||960;const cssWidth=Math.max(baseWidth,pointCount*86+110);const height=320;if(canvas.width!==Math.round(cssWidth*dpr)||canvas.height!==Math.round(height*dpr)){canvas.width=Math.round(cssWidth*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=cssWidth+'px';canvas.style.height=height+'px'}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,cssWidth,height);chartPoints=[];const pad={l:54,r:34,t:24,b:54};ctx.fillStyle='#0f1829';ctx.fillRect(0,0,cssWidth,height);ctx.strokeStyle='#263653';ctx.lineWidth=1;ctx.fillStyle='#aeb8ca';ctx.font='12px Malgun Gothic, Arial';for(let i=1;i<=5;i++){const y=pad.t+(5-i)*(height-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(cssWidth-pad.r,y);ctx.stroke();ctx.fillText(i+'점',14,y+4)}if(!records.length){$('trendInterpretation').textContent=resultEmptyMessage();return}const sorted=[...records].sort(compareRecordsAsc);sorted.forEach((r,i)=>{const x=sorted.length===1?(pad.l+cssWidth-pad.r)/2:pad.l+i*(cssWidth-pad.l-pad.r)/(sorted.length-1);const y=pad.t+(5-participationLevel(r))*(height-pad.t-pad.b)/4;chartPoints.push({x,y,record:r})});ctx.strokeStyle='#8ab4ff';ctx.lineWidth=3;ctx.beginPath();chartPoints.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.textAlign='center';ctx.textBaseline='top';ctx.font=sorted.length>8?'11px Malgun Gothic, Arial':'12px Malgun Gothic, Arial';chartPoints.forEach(p=>{const selected=selectedChartRecordId===p.record.id;const hovered=hoveredChartRecordId===p.record.id;const radius=selected?11:hovered?10:9;ctx.beginPath();ctx.fillStyle=selected?'#7cff9d':'#54d17a';ctx.strokeStyle=selected?'#ffffff':'#b7d8ff';ctx.lineWidth=selected?3:2.5;ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fill();ctx.stroke();if(selected){ctx.beginPath();ctx.strokeStyle='rgba(124,255,157,.38)';ctx.lineWidth=4;ctx.arc(p.x,p.y,radius+5,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#c7d0df';ctx.fillText(p.record.date.slice(5),p.x,height-34)});ctx.textAlign='start';ctx.textBaseline='alphabetic';$('trendInterpretation').textContent=periodMeta().label+' · 같은 날짜의 기록은 시간대 순서로 표시됩니다.'}
function showChartRecordDetail(r){selectedChartRecordId=r.id;const acts=activityList(r).join(', ')||'미선택';const strs=(r.strategies||[]).map(strategyLabel).join(', ')||'없음';$('chartDetail').classList.remove('hidden');$('chartDetail').innerHTML='<h4>선택한 기록</h4><dl><dt>날짜</dt><dd>'+escapeHtml(r.date)+'</dd><dt>학생 코드</dt><dd>'+escapeHtml(studentCode(r.studentId))+'</dd><dt>시간대</dt><dd>'+escapeHtml(r.period||'미기록')+'</dd><dt>과목</dt><dd>'+escapeHtml(subjectText(r))+'</dd><dt>참여 점수</dt><dd>'+participationLevel(r)+'점 '+escapeHtml(participationLabels[participationLevel(r)])+'</dd><dt>수업 활동 태그</dt><dd>'+escapeHtml(acts)+'</dd><dt>선택한 UDL 지원 전략</dt><dd>'+escapeHtml(strs)+'</dd></dl>'}

function dateDaysAgo(days){const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()-days);return date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0')}
function exampleData(){return [[110,2],[95,2],[80,3],[65,3],[50,2],[35,3],[28,2],[25,2],[22,3],[19,2],[16,3],[13,2],[11,3],[9,3],[7,4],[5,3],[3,4],[1,5]]}
function clearExampleRecords(){const exampleStudentIds=new Set(state.students.filter(isExampleItem).map(s=>s.id));state.records=state.records.filter(r=>!isExampleItem(r)&&!exampleStudentIds.has(r.studentId));state.students=state.students.filter(s=>!isExampleItem(s))}
function createExampleRecords(){clearExampleRecords();const student={id:uid(),code:'예시학생',grade:'예시',definition:'결과 화면 기능을 살펴보기 위한 예시 자료',isExample:true};state.students.push(student);const lowSupports=['표상 지원: 그래픽조직자','표상 지원: 활동 순서 시각화','표상 지원: 짧은 단계 제시','참여 지원: 또래 지원'];const highSupports=['공통 지원: 다양한 도구와 자료','참여 지원: 모델링 지원','참여 지원: 선택권 제공','공통 지원: 즉각적 피드백'];const middleSupports=['표상 지원: 짧은 단계 제시','참여 지원: 또래 지원','공통 지원: 다양한 도구와 자료'];const activities=['계산활동','읽기','만들기','발표·말하기'];const subjects=['수학','국어','통합교과','국어'];exampleData().forEach(([days,level],i)=>{const supportPool=level<=2?lowSupports:level>=4?highSupports:middleSupports;const strategies=[supportPool[i%supportPool.length]];if((level<=2||level>=4)&&i%3===0)strategies.push(supportPool[(i+1)%supportPool.length]);const low=level<=2;state.records.push({id:uid(),isExample:true,studentId:student.id,date:dateDaysAgo(days),period:(i%6+1)+'교시',subject:subjects[i%subjects.length],contextTags:activities[i%activities.length],toolMedia:activities[i%activities.length],strategies,participationLevel:level,participationRate:level,engagement:level,difficultyLevel:low?'3':'0',problemBehaviorCount:low?3:0,frequency:low?3:0,antecedent:low?'과제 설명 직후 활동 순서가 바뀜':'활동 시작 전 선택 방법을 안내함',behavior:low?'짧게 참여한 뒤 도움을 요청함':level>=4?'스스로 활동을 선택하고 참여함':'지원 후 주요 활동 참여가 이어짐',consequence:low?'시각화와 또래 지원 후 다시 참여함':level>=4?'선택권과 즉각적 피드백 후 참여가 유지됨':'짧은 단계 안내 후 활동을 이어감'})});return student.id}
function addExampleData(){const exampleId=createExampleRecords();showAllRecords=false;selectedChartRecordId=null;hoveredChartRecordId=null;clearChartDetail();localStorage.setItem(storeKey,JSON.stringify(state));render();$('resultStudentSelect').value=exampleId;resultSelectionTouched=true;renderResults()}
function removeExampleData(){const selected=selectedStudentId();const selectedWasExample=isExampleItem(studentById(selected));clearExampleRecords();const actualStudents=state.students.filter(s=>!isExampleItem(s));const next=selectedWasExample?(actualStudents[0]?.id||''):state.students.some(s=>s.id===selected)?selected:(actualStudents[0]?.id||'');showAllRecords=false;selectedChartRecordId=null;hoveredChartRecordId=null;clearChartDetail();localStorage.setItem(storeKey,JSON.stringify(state));render();$('resultStudentSelect').value=next;resultSelectionTouched=true;renderResults()}
function reportPeriodLabel(period){return period==='1month'?'최근 1개월':period==='all'?'전체 기록':'최근 2주'}
function reportAverage(records){return records.length?average(records).toFixed(1)+'점':'없음'}
function reportFlowText(records){if(!records.length)return'기록 없음';const recent=records.slice(-5);const levels=recent.map(participationLevel);if(levels.length<2)return'추가 기록 필요';const diff=levels.at(-1)-levels[0];const range=Math.max(...levels)-Math.min(...levels);if(range>=3)return'변동 있음';return diff>0?'상승 흐름':diff<0?'하락 흐름':'유지 흐름'}
function reportTopList(counts,empty,limit=3){return counts.length?'<ul>'+counts.slice(0,limit).map(([name,count])=>'<li><strong>'+escapeHtml(name)+'</strong><span>'+count+'회</span></li>').join('')+'</ul>':'<p class="report-empty">'+escapeHtml(empty)+'</p>'}
function reportAnalysis(records,period){const sorted=[...records].sort(compareRecordsAsc);const recent=sorted.slice(-5);const previous=sorted.slice(-10,-5);const levels=recent.map(participationLevel);const first=sorted[0];const last=sorted.at(-1);const high=sorted.filter(r=>participationLevel(r)>=4);const low=sorted.filter(r=>participationLevel(r)<=2);const frequentSupport=countItems(sorted,r=>(r.strategies||[]).map(strategyLabel));const highSupport=countItems(high,r=>(r.strategies||[]).map(strategyLabel));const lowActivities=countItems(low,activityList);const lowSubjects=countItems(low,r=>[subjectText(r)]);const lowSupports=countItems(low,r=>(r.strategies||[]).map(strategyLabel));const subjectStrength=strengthRows(sorted,r=>[subjectText(r)]);const activityStrength=strengthRows(sorted,r=>activityList(r));return{periodLabel:reportPeriodLabel(period),totalRecords:sorted.length,recent,previous,recentAverage:reportAverage(recent),previousAverage:previous.length?reportAverage(previous):'',trendType:reportFlowText(sorted),scoreFlow:levels.map(v=>v+'점').join(' → '),firstLevel:first?participationLevel(first):null,lastLevel:last?participationLevel(last):null,frequentSupport,highSupport,lowActivities,lowSubjects,lowSupports,subjectStrength,activityStrength}}
function reportTrendSentence(a){if(!a.totalRecords)return'선택한 기간에 기록이 없습니다. 수업 참여 기록을 추가한 뒤 다시 확인해 주세요.';if(a.totalRecords===1)return'기록이 1개이므로 참여 흐름을 판단하기보다는 해당 수업 장면의 참고 기록으로 확인해 주세요.';if(a.totalRecords<5)return'선택한 기간의 기록 수가 적어 흐름을 단정하기는 어렵습니다. 현재 기록에서는 '+a.firstLevel+'점에서 '+a.lastLevel+'점 사이의 변화가 나타났습니다.';const previous=a.previousAverage?' 이전 5회 평균은 '+a.previousAverage+'입니다.':'';return'최근 5회 평균은 '+a.recentAverage+'이며, 최근 흐름은 '+a.trendType+'으로 정리됩니다.'+previous+' 이 결과는 학생 평가가 아니라 수업 장면을 돌아보기 위한 참고 자료입니다.'}
function reportStrengthHtml(summary,empty){if(!summary.top.length)return'<p class="report-empty">'+escapeHtml(empty)+'</p>';return'<div class="report-strength-list">'+summary.top.slice(0,2).map((row,index)=>'<div class="report-strength-item '+(index===0?'best':'')+'"><span>'+(index===0?'높은 참여':'참고 장면')+'</span><strong>'+escapeHtml(row.name)+'</strong><p>최근 '+row.count+'회 기록 · 평균 '+row.avg.toFixed(1)+'점</p></div>').join('')+'</div>'}
function reportNextSuggestions(a){const suggestions=[];const high=a.highSupport.slice(0,2).map(([name])=>name);if(high.length)suggestions.push('높은 참여 기록에서 함께 나타난 '+high.join(', ')+'을 다음 수업에서도 유지하며 관찰해 보기');const lowActivity=a.lowActivities[0]?.[0];const lowSupport=a.lowSupports[0]?.[0];if(lowActivity)suggestions.push(lowActivity+' 장면에서는 과제 단계, 표현 방법, 지원 제공 시점을 짧게 조정해 보기');if(lowSupport)suggestions.push('낮은 참여 기록에서 함께 나타난 '+lowSupport+'은 제공 방식이나 강도를 바꾸어 다시 관찰해 보기');if(!suggestions.length)suggestions.push('같은 기준으로 기록을 조금 더 쌓아 참여 흐름과 수업 맥락을 함께 살펴보기');return suggestions.slice(0,3)}
function renderNextLessonDirections(records){const list=$('nextLessonDirections');if(!list)return;if(!records.length){list.innerHTML='<li>선택한 기간의 기록이 더 쌓이면 다음 수업에서 유지하거나 조정해 볼 방향을 확인할 수 있습니다.</li>';return}const analysis=reportAnalysis(records,selectedPeriod);list.innerHTML=reportNextSuggestions(analysis).map(item=>'<li>'+escapeHtml(item)+'</li>').join('')}
function reportContextHtml(records){const recent=[...records].reverse().slice(0,5);if(!recent.length)return'<section class="report-card report-card-wide report-context-card"><h3>상세 수업 맥락</h3><p class="report-empty">선택한 기간에 표시할 상세 기록이 없습니다.</p></section>';return'<section class="report-card report-card-wide report-context-card"><h3>상세 수업 맥락</h3><div class="report-context-list">'+recent.map(r=>{const acts=activityList(r).join(', ')||'미선택';const strs=(r.strategies||[]).map(strategyLabel).join(', ')||'없음';return'<article><header><strong>'+escapeHtml(r.date)+'</strong><span>'+escapeHtml(r.period||'시간 미기록')+' · '+escapeHtml(subjectText(r))+' · '+participationLevel(r)+'점 '+escapeHtml(participationLabels[participationLevel(r)])+'</span></header><dl><dt>수업 활동</dt><dd>'+escapeHtml(acts)+'</dd><dt>UDL 지원</dt><dd>'+escapeHtml(strs)+'</dd><dt>어려웠던 순간</dt><dd>'+escapeHtml(difficultyText(r))+'</dd><dt>선행사건</dt><dd>'+escapeHtml(r.antecedent||'기록 없음')+'</dd><dt>관찰된 참여 모습</dt><dd>'+escapeHtml(r.behavior||'기록 없음')+'</dd><dt>결과</dt><dd>'+escapeHtml(r.consequence||'기록 없음')+'</dd></dl></article>'}).join('')+'</div></section>'}
function reportCanvasData(records){const canvas=document.createElement('canvas');canvas.width=880;canvas.height=260;const ctx=canvas.getContext('2d');const width=canvas.width;const height=canvas.height;const pad={l:54,r:28,t:22,b:48};ctx.fillStyle='#ffffff';ctx.fillRect(0,0,width,height);ctx.strokeStyle='#d8dee9';ctx.lineWidth=1;ctx.fillStyle='#5b6575';ctx.font='13px Malgun Gothic, Arial';for(let i=1;i<=5;i++){const y=pad.t+(5-i)*(height-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(width-pad.r,y);ctx.stroke();ctx.fillText(i+'점',12,y+4)}if(!records.length){ctx.fillStyle='#5b6575';ctx.font='16px Malgun Gothic, Arial';ctx.fillText('이 기간에는 기록이 없습니다.',width/2-95,height/2);return canvas.toDataURL('image/png')}const sorted=[...records].sort(compareRecordsAsc);const points=sorted.map((r,i)=>({record:r,x:sorted.length===1?(pad.l+width-pad.r)/2:pad.l+i*(width-pad.l-pad.r)/(sorted.length-1),y:pad.t+(5-participationLevel(r))*(height-pad.t-pad.b)/4}));ctx.strokeStyle='#4f7cff';ctx.lineWidth=3;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.textAlign='center';ctx.textBaseline='top';ctx.font=sorted.length>10?'11px Malgun Gothic, Arial':'12px Malgun Gothic, Arial';points.forEach(p=>{ctx.beginPath();ctx.fillStyle='#54d17a';ctx.strokeStyle='#1f3f77';ctx.lineWidth=2.5;ctx.arc(p.x,p.y,7.5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#374151';ctx.fillText(p.record.date.slice(5),p.x,height-30)});ctx.textAlign='start';ctx.textBaseline='alphabetic';return canvas.toDataURL('image/png')}
function reportHtml(student,records,period){const a=reportAnalysis(records,period);const lowMixed=[...a.lowActivities.map(([n,c])=>['활동: '+n,c]),...a.lowSubjects.map(([n,c])=>['과목: '+n,c]),...a.lowSupports.map(([n,c])=>['함께 기록된 지원: '+n,c])].sort((x,y)=>y[1]-x[1]||x[0].localeCompare(y[0]));return '<header class="report-title"><p>UDL 수업 참여 관찰 보고서</p><h2>'+escapeHtml(student?.code||'학생')+'</h2><div class="report-meta-grid"><article><span>관찰 기간</span><strong>'+escapeHtml(a.periodLabel)+'</strong></article><article><span>총 기록</span><strong>'+a.totalRecords+'개</strong></article><article><span>최근 5회 평균</span><strong>'+escapeHtml(a.recentAverage)+'</strong></article><article><span>생성일</span><strong>'+today()+'</strong></article></div></header><section class="report-chart-card"><div class="report-card-head"><h3>전체 참여 흐름</h3><span>'+escapeHtml(a.periodLabel)+'</span></div><img class="report-chart" src="'+reportCanvasData(records)+'" alt="참여 변화 그래프"><div class="report-chart-summary"><p><strong>이전 5회 평균</strong><span>'+escapeHtml(a.previousAverage||'비교 기록 없음')+'</span></p><p><strong>변화 방향</strong><span>'+escapeHtml(a.trendType)+'</span></p><p><strong>최근 5회 점수 흐름</strong><span>'+escapeHtml(a.scoreFlow||'기록 없음')+'</span></p></div></section><section class="report-analysis-grid"><article class="report-card report-card-wide"><h3>참여 흐름 분석</h3><p>'+escapeHtml(reportTrendSentence(a))+'</p></article><article class="report-card"><h3>높은 참여 기록에서 함께 나타난 UDL 지원</h3>'+reportTopList(a.highSupport,'선택한 기간에는 4점 이상으로 기록된 장면이 충분하지 않습니다.')+'</article><article class="report-card"><h3>참여가 낮았던 수업 맥락</h3>'+reportTopList(lowMixed,'선택한 기간에는 1~2점으로 기록된 장면이 없습니다.')+'</article><article class="report-card report-card-wide"><h3>학생의 강점으로 보인 장면</h3><div class="report-strength-grid"><section><h4>강점으로 보인 과목</h4>'+reportStrengthHtml(a.subjectStrength,'분석할 수 있는 과목 기록이 없습니다.')+'</section><section><h4>강점으로 보인 활동</h4>'+reportStrengthHtml(a.activityStrength,'분석할 수 있는 활동 기록이 없습니다.')+'</section></div><p class="report-help">관찰 기간 동안 비교적 높은 참여가 나타난 장면입니다. 학생의 고정된 능력을 의미하지 않으며 수업 장면을 돌아보기 위한 참고 자료입니다.</p></article>'+reportContextHtml(records)+'</section><section class="report-card report-next-card"><h3>다음 수업에서 살펴볼 방향</h3><ol>'+reportNextSuggestions(a).map(item=>'<li>'+escapeHtml(item)+'</li>').join('')+'</ol></section>'}
function prepareReportAndPrint(){const id=selectedStudentId();if(!id||id==='all'){alert('보고서를 만들 학생을 선택해 주세요.');return}const student=studentById(id);const allRecords=recordsForStudent(id);const records=filterRecordsByPeriod(allRecords);if(!allRecords.length){alert('보고서로 정리할 기록이 없습니다.');return}let report=$('printReport');if(!report){report=document.createElement('section');report.id='printReport';document.body.append(report)}report.innerHTML=reportHtml(student,records,selectedPeriod);setTimeout(()=>window.print(),80)}
function downloadCsv(){const rows=[['날짜','학생코드','시간대','과목','참여점수','수업활동태그','UDL지원','어려웠던순간','수업전중상황','관찰된참여모습','결과']];state.records.filter(r=>!isExampleItem(r)).forEach(r=>rows.push([r.date,studentCode(r.studentId),r.period,subjectText(r),participationLevel(r)+'점 '+participationLabels[participationLevel(r)],activityList(r).join('|'),(r.strategies||[]).map(strategyLabel).join('|'),difficultyText(r),r.antecedent,r.behavior,r.consequence]));const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='udl-observation.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function backupData(){const exportState={students:state.students.filter(s=>!isExampleItem(s)),records:state.records.filter(r=>!isExampleItem(r))};const blob=new Blob([JSON.stringify({app:'UDL로 함께 성장하는 우리',version:2,revision:121,exportedAt:new Date().toISOString(),state:exportState},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='udl-record-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function restoreData(e){const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());const next=data.state||data;if(!Array.isArray(next.students)||!Array.isArray(next.records))throw new Error('invalid');if(confirm('백업 파일의 학생과 기록을 불러올까요?')){state={students:next.students,records:next.records};normalizeStoredData();save()}}catch{alert('백업 파일을 읽을 수 없습니다.')}finally{e.target.value=''}}
load();

